### ISSUE TITLE
Objective Function

### ISSUE THREAD

**Issue by kwan-0915** [pixelhero98/MGDPR#1]
Hello. I have a question related to the objective function in the paper (equation 6).

In the paper, you sum up all the losses in batch level then divide them by batch size, later you add up with theta. 

However, in your implementation, you add up both loss and theta in batch level (to my best understanding your implementation is based on full batch training), in train_val_test.py line 99 - 102.

I wonder if this is contradicted with equation 6 in the paper. 

Also, in train_val_test.py line 56 - 58, why the start date (sedate[0]), end date (sedate[1]) and dataset type (dataset_type[0]) for training, validation and test dataset are the same? 

Thank you.

**Comment by pixelhero98** [comment]
Hi,

Thank you for spotting these errors. There was an issue between the uploaded version and the oldest version, I didn't notice this happened. They should correspond to the designated type, i.e., train, val, and test. Also, the regularizer is not inside the loop.

**Comment by kwan-0915** [comment]
Hello. Thank you for your quick reply. 

I was wondering if you could share a runnable ipynb that put everything inside and reproduce the result please. 

Once again, thank you for sharing the code base, I have learnt a lot from it.
